// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNXS6ygb28Kt4a54kafSdbmCoPgQ9VcLM',
    appId: '1:454739289117:web:09b16b7c034fe056dc52f4',
    messagingSenderId: '454739289117',
    projectId: 'ecommerce-82a21',
    authDomain: 'ecommerce-82a21.firebaseapp.com',
    storageBucket: 'ecommerce-82a21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb4bnT0QNwQnQqTHfNI6Rq_MeEMb8uIq8',
    appId: '1:454739289117:android:810859e3b6fd23fadc52f4',
    messagingSenderId: '454739289117',
    projectId: 'ecommerce-82a21',
    storageBucket: 'ecommerce-82a21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhidim4nz0JOpM1OBogjeGlnwfM0UMxrw',
    appId: '1:454739289117:ios:86f34a0f5c960843dc52f4',
    messagingSenderId: '454739289117',
    projectId: 'ecommerce-82a21',
    storageBucket: 'ecommerce-82a21.appspot.com',
    iosClientId: '454739289117-ln4j5qc0e4v4vi3rksablrpk84tchbq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhidim4nz0JOpM1OBogjeGlnwfM0UMxrw',
    appId: '1:454739289117:ios:86f34a0f5c960843dc52f4',
    messagingSenderId: '454739289117',
    projectId: 'ecommerce-82a21',
    storageBucket: 'ecommerce-82a21.appspot.com',
    iosClientId: '454739289117-ln4j5qc0e4v4vi3rksablrpk84tchbq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
